networks:
    sophie-wordpress-v2:
        driver: bridge

services:
    mysql:
        image: mysql:8
        container_name: sophie-wordpress-v2-mysql
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - sophie-wordpress-v2

    server:
        build: 
          context: .
        container_name: sophie-wordpress-v2-wordpress
        ports:
            - "80:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_HOST: sophie-wordpress-v2-mysql
        depends_on:
            - mysql
        networks:
            - sophie-wordpress-v2

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sophie-wordpress-v2-phpmyadmin
        ports:
            - "8000:80"
        environment:
            PMA_HOST: sophie-wordpress-v2-mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        depends_on:
            - mysql
        networks:
            - sophie-wordpress-v2